### ISSUE TITLE
GetBook должно быть query, а не mutation

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/graphql#3]
https://github.com/KatiaSychik/graphql/blob/df1220dcf6713f5f224e6fdf953a45f2e450cf92/app/graphql/mutations/get_book.rb#L1-L2

GetBook не изменяет никаких данных, в REST-e это был бы обычный GET запрос, поэтому и здесь это должно быть query, а не mutation.

**Comment by KatiaSychik** [comment]
f8a4c3118b752ef3e15ba0e806aaddf47864e180
